### ISSUE TITLE
Design frontend layout

### ISSUE THREAD

**Issue by apzsfo** [scalableinternetservices/spartify#5]

**Comment by danielskathyd** [comment]
Designs created for
1. Main page with popups for creating a party and joining a party with optional passwords
2. Individual party page with columns displaying song library, song queue with votes shown, and listening history

<img width="726" alt="Screen Shot 2020-10-16 at 3 56 49 PM" src="https://user-images.githubusercontent.com/32717893/96781916-ff5ed700-13a1-11eb-88df-27ff8bd64d72.png">
<img width="729" alt="Screen Shot 2020-10-16 at 3 56 45 PM" src="https://user-images.githubusercontent.com/32717893/96781921-ff5ed700-13a1-11eb-9963-57aceef3da0a.png">
<img width="671" alt="Screen Shot 2020-10-16 at 3 11 42 PM" src="https://user-images.githubusercontent.com/32717893/96781902-fe2daa00-13a1-11eb-8a0a-fb88fee7fdbf.png">
